/*CRIANDO BANCO DE DADOS*/
CREATE DATABASE LOJADEINFORMATICA
/*USANDO BANCO DE DADOS*/
USE LOJADEINFORMATICA
/*CRIANDO AS TABELAS DO BANCO DE DADOS*/
CREATE TABLE FUNCIONARIO(
COD_FUNC INT PRIMARY KEY IDENTITY,
NOME_FUNC VARCHAR(50)
)
CREATE TABLE CLIENTE(
COD_CLI INT PRIMARY KEY IDENTITY,
NOME_CLI VARCHAR(50),
QUANT_CLI INT
)
CREATE TABLE MERCADORIA(	
COD_MERC INT PRIMARY KEY IDENTITY,
NOME_MERC VARCHAR(50),
QUANT_MERC INT
)
CREATE TABLE PEDIDO(
COD_PED INT PRIMARY KEY IDENTITY,
DESC_PED VARCHAR(50),
VALOR_PED FLOAT,
FK_COD_MERC INT,
FK_COD_CLI INT
FOREIGN KEY(FK_COD_MERC) REFERENCES MERCADORIA(COD_MERC),
FOREIGN KEY(FK_COD_CLI) REFERENCES CLIENTE(COD_CLI),
)
CREATE TABLE VENDA(
COD_VEND INT PRIMARY KEY IDENTITY,
DESC_VEND VARCHAR(50),
FORMA_VEND VARCHAR(20),
FK_COD_PED INT,
FOREIGN KEY (FK_COD_PED) REFERENCES PEDIDO(COD_PED)
)
/*CONSULTANDO AS TABELAS DO BANCO DE DADOS*/
SELECT * FROM FUNCIONARIO
SELECT * FROM CLIENTE
SELECT * FROM MERCADORIA
SELECT * FROM PEDIDO
SELECT * FROM VENDA