/*CRIANDO BANCO DE DADOS*/
CREATE DATABASE LOJADEINFORMATICA
/*USANDO BANCO DE DADOS*/
USE LOJADEINFORMATICA
/*CRIANDO AS TABELAS DO BANCO DE DADOS*/
CREATE TABLE FUNCIONARIO(
COD_FUNC INT PRIMARY KEY IDENTITY,
NOME_FUNC VARCHAR(50)
)
CREATE TABLE CLIENTE(
COD_CLI INT PRIMARY KEY IDENTITY,
NOME_CLI VARCHAR(50),
QUANT_CLI INT
)
CREATE TABLE MERCADORIA(	
COD_MERC INT PRIMARY KEY IDENTITY,
NOME_MERC VARCHAR(50),
QUANT_MERC INT
)
CREATE TABLE PEDIDO(
COD_PED INT PRIMARY KEY IDENTITY,
DESC_PED VARCHAR(50),
VALOR_PED FLOAT,
FK_COD_MERC INT,
FK_COD_CLI INT
FOREIGN KEY(FK_COD_MERC) REFERENCES MERCADORIA(COD_MERC),
FOREIGN KEY(FK_COD_CLI) REFERENCES CLIENTE(COD_CLI),
)
CREATE TABLE VENDA(
COD_VEND INT PRIMARY KEY IDENTITY,
DESC_VEND VARCHAR(50),
FORMA_VEND VARCHAR(20),
FK_COD_PED INT,
FOREIGN KEY (FK_COD_PED) REFERENCES PEDIDO(COD_PED)
)
/*CONSULTANDO AS TABELAS DO BANCO DE DADOS*/
SELECT * FROM FUNCIONARIO
SELECT * FROM CLIENTE
SELECT * FROM MERCADORIA
SELECT * FROM PEDIDO
SELECT * FROM VENDA

/*INSERINDO INFORMAÇÕES NAS TABELAS*/

INSERT INTO FUNCIONARIO(NOME_FUNC) VALUES('VICTOR')
INSERT INTO FUNCIONARIO(NOME_FUNC) VALUES('KAIO')
INSERT INTO FUNCIONARIO(NOME_FUNC) VALUES('NICOLAS')

INSERT INTO CLIENTE(NOME_CLI,EMAIL) VALUES('RYAN','RYAN@GMAIL.COM')
INSERT INTO CLIENTE(NOME_CLI,EMAIL) VALUES('LAYSA','LAYSA@GMAIL.COM')
INSERT INTO CLIENTE(NOME_CLI,EMAIL) VALUES('GABRIEL','GABRIEL@GMAIL.COM')
INSERT INTO CLIENTE(NOME_CLI,EMAIL) VALUES('ISIS','ISIS@GMAIL.COM')

INSERT INTO MERCADORIA(NOME_MERC,QUANT_MERC) VALUES('TECLADO MECÂNICO',100)
INSERT INTO MERCADORIA(NOME_MERC,QUANT_MERC) VALUES('MOUSE',80)
INSERT INTO MERCADORIA(NOME_MERC,QUANT_MERC) VALUES('FONE DE OUVIDO',90)
INSERT INTO MERCADORIA(NOME_MERC,QUANT_MERC) VALUES('CARREGADOR DE CELULAR',70)

INSERT INTO PEDIDO(DESC_PED,VALOR_PED,FK_COD_MERC,FK_COD_CLI)
VALUES('TECLADO MECÂNICO GAMER T-DAGGER',219.90,1,1)

INSERT INTO PEDIDO(DESC_PED,VALOR_PED,FK_COD_MERC,FK_COD_CLI)
VALUES('MOUSE REDRAGON',189.90,2,2)

INSERT INTO PEDIDO(DESC_PED,VALOR_PED,FK_COD_MERC,FK_COD_CLI)
VALUES('FONE DE OUVIDO JBL',40.00,3,1)

INSERT INTO PEDIDO(DESC_PED,VALOR_PED,FK_COD_MERC,FK_COD_CLI)
VALUES('CARREGADOR SAMSUNG',81.00,4,3)

INSERT INTO VENDA(DESC_VEND,FORMA_VEND,FK_COD_PED)
VALUES('VENDA DE UM TECLADO MECÂNICO','DINHEIRO',9)

INSERT INTO VENDA(DESC_VEND,FORMA_VEND,FK_COD_PED)
VALUES('VENDA DE UM MOUSE REDRAGON','DINHEIRO',11)

INSERT INTO VENDA(DESC_VEND,FORMA_VEND,FK_COD_PED)
VALUES('VENDA DE UM CARREGADOR SAMSUNG','DINHEIRO',12)

/*ALTERAÇÕES NAS TABELAS DO BANCO DE DADOS*/
ALTER TABLE CLIENTE
ADD EMAIL VARCHAR(50);

SELECT NOME_CLI,NOME_FUNC
FROM CLIENTE,FUNCIONARIO
WHERE CLIENTE.COD_CLI = FUNCIONARIO.COD_FUNC		